[project]
name = "linkedinbot"
version = "0.1.0"
description = "LinkedIn automation tool to automatically connect with professionals in selected roles."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "selenium>=4.35.0",
    "webdriver-manager>=4.0.2",
]
